[ 2020-12-03 13:37:23,301 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Narrowband imaging commissioning and engineering test
 pool_resources: bluse_1,cbf_1,fbfuse_1,sdp_1 and 52 antennas
 active_sbs: 20201202-0014
 script_name: /usr/local/bin/astrokat-observe.py
 script_status: interrupted
 Duration: 0:31:00.599912```
[ 2020-12-03 14:10:16,901 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: apsuse_1,cbf_1,fbfuse_1,sdp_1,tuse_1 and 55 antennas
 active_sbs: 20201203-0040
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:05:11.404188```
[ 2020-12-03 15:00:44,894 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,sdp_1 and 58 antennas
 active_sbs: 20201203-0041
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:05:36.784391```
[ 2020-12-03 18:09:57,695 - INFO]  *subarray_1: Completed:* 
 ``` script_description:  L-band holography tracktime 5 elevation histogram
 pool_resources: cbf_1,sdp_1 and 58 antennas
 active_sbs: 20201203-0042
 script_name: /home/kat/katsdpscripts/observation/spiral_holography_scan.py
 script_status: interrupted
 Duration: 3:05:07.396577```
[ 2020-12-03 18:42:38,698 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 59 antennas
 active_sbs: 20201203-0043
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:05:52.588761```
[ 2020-12-03 19:00:31,306 - INFO]  *subarray_1: Completed:* 
 ``` script_description: pointing check on J1939-6342
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 59 antennas
 active_sbs: 20201203-0044
 script_name: /home/kat/katsdpscripts/observation/reference_pointing.py
 script_status: completed
 Duration: 0:16:09.808265```
[ 2020-12-04 00:37:40,510 - INFO]  *subarray_1: Completed:* 
 ``` script_description: MHONGOOSE J0546-52 setting 4
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 59 antennas
 active_sbs: 20201203-0008
 script_name: /usr/local/bin/astrokat-observe.py
 script_status: completed
 Duration: 5:35:28.002069```
[ 2020-12-04 01:23:44,101 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,sdp_1 and 59 antennas
 active_sbs: 20201203-0046
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:06:15.194129```
[ 2020-12-04 04:49:31,713 - INFO]  *subarray_1: Completed:* 
 ``` script_description:  UHF-band holography --scan-extent 15 --tracktime 5 --cycle-duration 2700 elevation-histogram
 pool_resources: cbf_1,sdp_1 and 59 antennas
 active_sbs: 20201203-0047
 script_name: /home/kat/katsdpscripts/observation/spiral_holography_scan.py
 script_status: interrupted
 Duration: 3:24:10.409853```
[ 2020-12-04 05:13:48,506 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,ptuse_2,sdp_1 and 59 antennas
 active_sbs: 20201204-0001
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:05:31.596010```
[ 2020-12-04 05:22:48,906 - INFO]  *subarray_1: Completed:* 
 ``` script_description: UHF Phase up with flatten bandpass
 pool_resources: cbf_1,ptuse_2,sdp_1 and 59 antennas
 active_sbs: 20201204-0002
 script_name: /home/kat/katsdpscripts/observation/bf_phaseup.py
 script_status: completed
 Duration: 0:06:56.999748```
[ 2020-12-04 06:58:05,309 - INFO]  *subarray_1: Completed:* 
 ``` script_description: COM-20191129-MG-01 UHF 1K TAB coherency
 pool_resources: cbf_1,ptuse_2,sdp_1 and 59 antennas
 active_sbs: 20201204-0003
 script_name: /home/kat/usersnfs/mgeyer/katusescripts/ptuse/beamform_coherency.py
 script_status: completed
 Duration: 1:29:18.801797```
[ 2020-12-04 07:41:04,908 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,sdp_1 and 59 antennas
 active_sbs: 20201204-0004
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:05:47.197163```
[ 2020-12-04 15:52:29,312 - INFO]  *subarray_2: Completed:* 
 ``` script_description: three calibrator imaging
 pool_resources: cbf_2,sdp_2 and 1 antennas
 active_sbs: 20201202-0023
 script_name: /home/kat/katsdpscripts/observation/track.py
 script_status: completed
 Duration: 0:12:13.198625```
[ 2020-12-04 16:36:03,321 - INFO]  *subarray_2: Completed:* 
 ``` script_description: three calibrator imaging
 pool_resources: cbf_2,sdp_2 and 1 antennas
 active_sbs: 20201204-0008
 script_name: /home/kat/katsdpscripts/observation/track.py
 script_status: completed
 Duration: 0:12:38.794896```
[ 2020-12-04 18:27:17,316 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Galactic Centre HI Clouds
 pool_resources: cbf_1,sdp_1 and 59 antennas
 active_sbs: 20201202-0002
 script_name: /usr/local/bin/astrokat-observe.py
 script_status: completed
 Duration: 10:24:06.608454```
[ 2020-12-04 19:05:02,736 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 61 antennas
 active_sbs: 20201204-0011
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:05:28.007644```
[ 2020-12-04 19:15:43,323 - INFO]  *subarray_1: Completed:* 
 ``` script_description: pointing check on J0408-6545
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 61 antennas
 active_sbs: 20201204-0010
 script_name: /home/kat/katsdpscripts/observation/reference_pointing.py
 script_status: completed
 Duration: 0:09:04.992655```
[ 2020-12-05 00:28:55,731 - INFO]  *subarray_1: Completed:* 
 ``` script_description: mfs07a
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 61 antennas
 active_sbs: 20201119-0004
 script_name: /usr/local/bin/astrokat-observe.py
 script_status: completed
 Duration: 5:10:19.002182```
[ 2020-12-05 00:37:24,822 - ERROR] Failed to push to Slack
[ 2020-12-05 00:37:24,822 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18d3250>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 02:06:04,927 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,ptuse_2,sdp_1 and 58 antennas
 active_sbs: 20201204-0014
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:05:23.798360```
[ 2020-12-05 02:14:34,070 - ERROR] Failed to push to Slack
[ 2020-12-05 02:14:34,070 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18d3ad0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 02:14:38,523 - INFO]  *subarray_1: Completed:* 
 ``` script_description: UHF Phase up with flatten bandpass
 pool_resources: cbf_1,ptuse_2,sdp_1 and 58 antennas
 active_sbs: 20201204-0015
 script_name: /home/kat/katsdpscripts/observation/bf_phaseup.py
 script_status: completed
 Duration: 0:00:04.451090```
[ 2020-12-05 02:23:07,605 - ERROR] Failed to push to Slack
[ 2020-12-05 02:23:07,606 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18d3410>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 03:15:20,322 - INFO]  *subarray_1: Completed:* 
 ``` script_description: COM-20191129-MG-01 UHF 1K TAB coherency
 pool_resources: cbf_1,ptuse_2,sdp_1 and 58 antennas
 active_sbs: 20201204-0016
 script_name: /home/kat/usersnfs/mgeyer/katusescripts/ptuse/beamform_coherency.py
 script_status: interrupted
 Duration: 0:52:12.714977```
[ 2020-12-05 03:23:49,462 - ERROR] Failed to push to Slack
[ 2020-12-05 03:23:49,462 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec710>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 03:44:20,124 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: apsuse_1,cbf_1,fbfuse_1,sdp_1,tuse_1 and 61 antennas
 active_sbs: 20201205-0002
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:05:45.799400```
[ 2020-12-05 03:52:49,238 - ERROR] Failed to push to Slack
[ 2020-12-05 03:52:49,238 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecf50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 03:52:49,240 - INFO]  *subarray_1: Completed:* 
 ``` pool_resources: apsuse_1,cbf_1,fbfuse_1,sdp_1,tuse_1 and 61 antennas
 active_sbs: 20201205-0003
 script_status: completed
 Duration: 0:00:00.000350```
[ 2020-12-05 04:01:18,422 - ERROR] Failed to push to Slack
[ 2020-12-05 04:01:18,422 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec390>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 07:15:44,128 - INFO]  *subarray_1: Completed:* 
 ``` script_description: TRAPUM Fermi Sources: Shallow Survey Pass 2 Block 3
 pool_resources: apsuse_1,cbf_1,fbfuse_1,sdp_1,tuse_1 and 61 antennas
 active_sbs: 20201119-0030
 script_name: /usr/local/bin/astrokat-observe.py
 script_status: completed
 Duration: 3:14:25.704041```
[ 2020-12-05 07:24:13,141 - ERROR] Failed to push to Slack
[ 2020-12-05 07:24:13,142 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec110>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 07:38:52,327 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,fbfuse_1,ptuse_1,ptuse_3,sdp_1,tuse_1 and 31 antennas
 active_sbs: 20201205-0009
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:05:26.393198```
[ 2020-12-05 07:47:21,302 - ERROR] Failed to push to Slack
[ 2020-12-05 07:47:21,302 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec710>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 07:47:21,303 - INFO]  *subarray_2: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_2,ptuse_2,ptuse_4,sdp_2 and 30 antennas
 active_sbs: 20201205-0008
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:13:53.963007```
[ 2020-12-05 07:55:50,230 - ERROR] Failed to push to Slack
[ 2020-12-05 07:55:50,230 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecf50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 07:55:50,235 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Sub1: Meertime phase up with flatten bandpass
 pool_resources: cbf_1,fbfuse_1,ptuse_1,ptuse_3,sdp_1,tuse_1 and 31 antennas
 active_sbs: 20201205-0004
 script_name: /home/kat/katsdpscripts/observation/bf_phaseup.py
 script_status: completed
 Duration: 0:00:00.002431```
[ 2020-12-05 08:04:19,414 - ERROR] Failed to push to Slack
[ 2020-12-05 08:04:19,414 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec390>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 08:04:19,417 - INFO]  *subarray_2: Completed:* 
 ``` script_description: Sub2: Meertime phase up with flatten bandpass
 pool_resources: cbf_2,ptuse_2,ptuse_4,sdp_2 and 30 antennas
 active_sbs: 20201205-0006
 script_name: /home/kat/katsdpscripts/observation/bf_phaseup.py
 script_status: completed
 Duration: 0:08:29.182893```
[ 2020-12-05 08:12:48,598 - ERROR] Failed to push to Slack
[ 2020-12-05 08:12:48,598 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec110>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 08:12:48,600 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Sub1: Fluxcal J1939-6342
 pool_resources: cbf_1,fbfuse_1,ptuse_1,ptuse_3,sdp_1,tuse_1 and 31 antennas
 active_sbs: 20201205-0005
 script_name: /home/kat/usersnfs/sarah/beamform-multi-cal/katusescripts/ptuse/beamform_multi_cal.py
 script_status: completed
 Duration: 0:08:29.183688```
[ 2020-12-05 08:21:17,781 - ERROR] Failed to push to Slack
[ 2020-12-05 08:21:17,782 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec710>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 08:21:17,783 - INFO]  *subarray_2: Completed:* 
 ``` script_description: Sub2: Fluxcal J1939-6342
 pool_resources: cbf_2,ptuse_2,ptuse_4,sdp_2 and 30 antennas
 active_sbs: 20201205-0007
 script_name: /home/kat/usersnfs/sarah/beamform-multi-cal/katusescripts/ptuse/beamform_multi_cal.py
 script_status: completed
 Duration: 0:08:29.183664```
[ 2020-12-05 08:29:46,965 - ERROR] Failed to push to Slack
[ 2020-12-05 08:29:46,966 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecf50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 12:50:20,932 - INFO]  *subarray_1: Completed:* 
 ``` script_description: MeerTIME TPA 15-17 LST  Sub1  (ptuse 1.3)  (epoch 9)
 pool_resources: cbf_1,fbfuse_1,ptuse_1,ptuse_3,sdp_1,tuse_1 and 31 antennas
 active_sbs: 20201204-0006
 script_name: /home/kat/usersnfs/sarah/multi/katusescripts/ptuse/beamform_multi.py
 script_status: interrupted
 Duration: 4:20:33.963215```
[ 2020-12-05 12:58:50,070 - ERROR] Failed to push to Slack
[ 2020-12-05 12:58:50,070 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec390>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 12:58:50,072 - INFO]  *subarray_2: Completed:* 
 ``` script_description: MeerTIME TPA 15-17  LST  Sub2  (ptuse 2.4)  (epoch 9)
 pool_resources: cbf_2,ptuse_2,ptuse_4,sdp_2 and 30 antennas
 active_sbs: 20201204-0005
 script_name: /home/kat/usersnfs/sarah/multi/katusescripts/ptuse/beamform_multi.py
 script_status: interrupted
 Duration: 4:29:03.103671```
[ 2020-12-05 13:07:19,254 - ERROR] Failed to push to Slack
[ 2020-12-05 13:07:19,254 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec110>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 13:14:27,532 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 61 antennas
 active_sbs: 20201205-0010
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:06:40.187749```
[ 2020-12-05 13:22:56,729 - ERROR] Failed to push to Slack
[ 2020-12-05 13:22:56,730 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec710>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 14:27:18,934 - INFO]  *subarray_1: Completed:* 
 ``` script_description: ThunderKAT XRB 2020-12-05
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 61 antennas
 active_sbs: 20201204-0009
 script_name: /usr/local/bin/astrokat-observe.py
 script_status: completed
 Duration: 1:04:22.202227```
[ 2020-12-05 14:35:48,054 - ERROR] Failed to push to Slack
[ 2020-12-05 14:35:48,054 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecf50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 14:54:53,533 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 59 antennas
 active_sbs: 20201205-0011
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:05:52.395368```
[ 2020-12-05 15:03:22,710 - ERROR] Failed to push to Slack
[ 2020-12-05 15:03:22,710 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec390>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 15:07:58,534 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Meertime phase up with flatten bandpass
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 59 antennas
 active_sbs: 20201205-0013
 script_name: /home/kat/katsdpscripts/observation/bf_phaseup.py
 script_status: completed
 Duration: 0:04:35.822018```
[ 2020-12-05 15:16:27,478 - ERROR] Failed to push to Slack
[ 2020-12-05 15:16:27,478 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec110>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 15:16:27,481 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Fluxcal J0408-6545
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 59 antennas
 active_sbs: 20201205-0014
 script_name: /home/kat/usersnfs/sarah/beamform-multi-cal/katusescripts/ptuse/beamform_multi_cal.py
 script_status: completed
 Duration: 0:00:00.000711```
[ 2020-12-05 15:24:56,534 - ERROR] Failed to push to Slack
[ 2020-12-05 15:24:56,534 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec710>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 16:44:35,336 - INFO]  *subarray_1: Completed:* 
 ``` script_description: MeerTime Relbin 2020-11-30 UHF
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 59 antennas
 active_sbs: 20201130-0022
 script_name: /home/kat/usersnfs/sarah/multi/katusescripts/ptuse/beamform_multi.py
 script_status: completed
 Duration: 1:19:38.799470```
[ 2020-12-05 16:53:04,470 - ERROR] Failed to push to Slack
[ 2020-12-05 16:53:04,470 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecf50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 17:19:10,336 - INFO]  *subarray_1: Completed:* 
 ``` script_description: pointing check on J1939-6342
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 59 antennas
 active_sbs: 20201205-0015
 script_name: /home/kat/katsdpscripts/observation/reference_pointing.py
 script_status: completed
 Duration: 0:26:05.864013```
[ 2020-12-05 17:27:39,478 - ERROR] Failed to push to Slack
[ 2020-12-05 17:27:39,478 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec390>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 17:41:59,541 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 61 antennas
 active_sbs: 20201205-0016
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:05:26.184184```
[ 2020-12-05 17:50:28,693 - ERROR] Failed to push to Slack
[ 2020-12-05 17:50:28,694 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec110>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 18:00:54,741 - INFO]  *subarray_1: Completed:* 
 ``` script_description: pointing check on J1939-6342
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 61 antennas
 active_sbs: 20201205-0018
 script_name: /home/kat/katsdpscripts/observation/reference_pointing.py
 script_status: completed
 Duration: 0:10:26.045116```
[ 2020-12-05 18:09:23,798 - ERROR] Failed to push to Slack
[ 2020-12-05 18:09:23,798 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec710>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-05 23:15:46,346 - INFO]  *subarray_1: Completed:* 
 ``` script_description: mfs06a
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 61 antennas
 active_sbs: 20201130-0026
 script_name: /usr/local/bin/astrokat-observe.py
 script_status: completed
 Duration: 5:06:22.545698```
[ 2020-12-05 23:24:15,445 - ERROR] Failed to push to Slack
[ 2020-12-05 23:24:15,446 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecf50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-06 04:55:12,549 - INFO]  *subarray_1: Completed:* 
 ``` script_description: MHONGOOSE J0409-27 setting 1
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 61 antennas
 active_sbs: 20201127-0034
 script_status: completed
 Duration: 5:30:57.101732```
[ 2020-12-06 05:03:41,653 - ERROR] Failed to push to Slack
[ 2020-12-06 05:03:41,654 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec390>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-06 05:21:57,946 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 61 antennas
 active_sbs: 20201206-0002
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:05:09.997612```
[ 2020-12-06 05:30:27,030 - ERROR] Failed to push to Slack
[ 2020-12-06 05:30:27,030 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec110>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-06 05:47:34,147 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Meertime phase up with flatten bandpass
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 61 antennas
 active_sbs: 20201206-0004
 script_name: /home/kat/katsdpscripts/observation/bf_phaseup.py
 script_status: completed
 Duration: 0:06:56.799354```
[ 2020-12-06 05:56:03,286 - ERROR] Failed to push to Slack
[ 2020-12-06 05:56:03,286 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec710>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-06 05:56:05,556 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Fluxcal J0408-6545
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 61 antennas
 active_sbs: 20201206-0005
 script_name: /home/kat/usersnfs/sarah/beamform-multi-cal/katusescripts/ptuse/beamform_multi_cal.py
 script_status: completed
 Duration: 0:00:02.268824```
[ 2020-12-06 06:04:34,773 - ERROR] Failed to push to Slack
[ 2020-12-06 06:04:34,774 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecf50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-06 07:45:39,348 - INFO]  *subarray_1: Completed:* 
 ``` script_description: MeerTime Relbin 2020-11-30
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 61 antennas
 active_sbs: 20201130-0021
 script_name: /home/kat/usersnfs/sarah/multi/katusescripts/ptuse/beamform_multi.py
 script_status: completed
 Duration: 1:41:04.572390```
[ 2020-12-06 07:54:08,469 - ERROR] Failed to push to Slack
[ 2020-12-06 07:54:08,470 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec390>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-06 08:22:01,549 - INFO]  *subarray_1: Completed:* 
 ``` script_description: pointing check on J1939-6342
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 61 antennas
 active_sbs: 20201206-0007
 script_name: /home/kat/katsdpscripts/observation/reference_pointing.py
 script_status: completed
 Duration: 0:16:53.400092```
[ 2020-12-06 08:30:30,742 - ERROR] Failed to push to Slack
[ 2020-12-06 08:30:30,742 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec110>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-06 08:58:36,549 - INFO]  *subarray_1: Completed:* 
 ``` pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 61 antennas
 active_sbs: 20201206-0008
 script_status: completed
 Duration: 0:28:05.805270```
[ 2020-12-06 09:07:05,686 - ERROR] Failed to push to Slack
[ 2020-12-06 09:07:05,686 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec710>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-06 09:33:06,758 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: apsuse_1,cbf_1,fbfuse_1,ptuse_1,ptuse_4,sdp_1,tuse_1 and 61 antennas
 active_sbs: 20201206-0006
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:05:16.404150```
[ 2020-12-06 09:41:35,958 - ERROR] Failed to push to Slack
[ 2020-12-06 09:41:35,958 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecf50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-06 10:04:05,352 - INFO]  *subarray_1: Completed:* 
 ``` script_description: TRAPUM phase up with flatten bandpass
 pool_resources: apsuse_1,cbf_1,fbfuse_1,ptuse_1,ptuse_4,sdp_1,tuse_1 and 61 antennas
 active_sbs: 20201206-0011
 script_name: /home/kat/katsdpscripts/observation/bf_phaseup.py
 script_status: completed
 Duration: 0:08:06.802675```
[ 2020-12-06 10:12:34,518 - ERROR] Failed to push to Slack
[ 2020-12-06 10:12:34,518 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec390>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-06 14:13:40,355 - INFO]  *subarray_1: Completed:* 
 ``` script_description: TRAPUM Globular Clusters: M28 (epoch 1/2)
 pool_resources: apsuse_1,cbf_1,fbfuse_1,ptuse_1,ptuse_4,sdp_1,tuse_1 and 61 antennas
 active_sbs: 20201130-0013
 script_name: /home/kat/usersnfs/sarah/multi/katusescripts/ptuse/beamform_multi.py
 script_status: completed
 Duration: 4:01:05.834832```
[ 2020-12-06 14:22:09,493 - ERROR] Failed to push to Slack
[ 2020-12-06 14:22:09,494 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec110>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-06 14:33:17,354 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,sdp_1 and 61 antennas
 active_sbs: 20201206-0012
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:06:45.398325```
[ 2020-12-06 14:41:46,581 - ERROR] Failed to push to Slack
[ 2020-12-06 14:41:46,582 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ece10>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-06 17:36:03,361 - INFO]  *subarray_1: Completed:* 
 ``` script_description: L-band Interferometric Pointing Calibration
 pool_resources: cbf_1,sdp_1 and 61 antennas
 active_sbs: 20201206-0013
 script_name: /home/kat/katsdpscripts/observation/interferometric_pointing.py
 script_status: completed
 Duration: 2:54:16.777422```
[ 2020-12-06 17:44:32,473 - ERROR] Failed to push to Slack
[ 2020-12-06 17:44:32,474 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec050>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-06 17:59:12,976 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 60 antennas
 active_sbs: 20201206-0014
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:05:53.008485```
[ 2020-12-06 18:07:42,166 - ERROR] Failed to push to Slack
[ 2020-12-06 18:07:42,166 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec710>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-06 18:07:42,168 - INFO]  *subarray_1: Completed:* 
 ``` pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 60 antennas
 active_sbs: 20201206-0015
 script_status: interrupted
 Duration: 0:00:00.000370```
[ 2020-12-06 18:16:11,094 - ERROR] Failed to push to Slack
[ 2020-12-06 18:16:11,094 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecf50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-06 18:16:11,096 - INFO]  *subarray_1: Completed:* 
 ``` pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 60 antennas
 active_sbs: 20201206-0016
 script_status: interrupted
 Duration: 0:00:00.000375```
[ 2020-12-06 18:24:40,278 - ERROR] Failed to push to Slack
[ 2020-12-06 18:24:40,278 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec6d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-06 18:24:40,280 - INFO]  *subarray_1: Completed:* 
 ``` pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 60 antennas
 active_sbs: 20201206-0017
 script_status: interrupted
 Duration: 0:00:00.000402```
[ 2020-12-06 18:33:09,462 - ERROR] Failed to push to Slack
[ 2020-12-06 18:33:09,462 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec050>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-06 18:33:34,971 - INFO]  *subarray_1: Completed:* 
 ``` pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 60 antennas
 active_sbs: 20201206-0018
 script_status: completed
 Duration: 0:00:25.507276```
[ 2020-12-06 18:42:04,118 - ERROR] Failed to push to Slack
[ 2020-12-06 18:42:04,118 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec710>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-06 23:47:00,566 - INFO]  *subarray_1: Completed:* 
 ``` script_description: mfs13a
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 60 antennas
 active_sbs: 20201130-0027
 script_name: /usr/local/bin/astrokat-observe.py
 script_status: completed
 Duration: 5:04:56.445126```
[ 2020-12-06 23:55:29,749 - ERROR] Failed to push to Slack
[ 2020-12-06 23:55:29,750 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecf50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 05:25:07,605 - INFO]  *subarray_1: Completed:* 
 ``` script_description: MHONGOOSE J0429-27 setting 2
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 60 antennas
 active_sbs: 20201203-0026
 script_status: completed
 Duration: 5:29:37.851877```
[ 2020-12-07 05:33:36,726 - ERROR] Failed to push to Slack
[ 2020-12-07 05:33:36,726 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec6d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 05:51:51,367 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,sdp_1 and 60 antennas
 active_sbs: 20201206-0019
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:05:59.183987```
[ 2020-12-07 06:00:20,566 - ERROR] Failed to push to Slack
[ 2020-12-07 06:00:20,566 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecc50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 07:48:16,168 - INFO]  *subarray_1: Completed:* 
 ``` script_description:  L-band holography tracktime 5 elevation histogram
 pool_resources: cbf_1,sdp_1 and 60 antennas
 active_sbs: 20201207-0002
 script_name: /home/kat/katsdpscripts/observation/spiral_holography_scan.py
 script_status: interrupted
 Duration: 1:47:55.599869```
[ 2020-12-07 07:56:45,141 - ERROR] Failed to push to Slack
[ 2020-12-07 07:56:45,142 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18eca90>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 08:19:28,379 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,sdp_1 and 55 antennas
 active_sbs: 20201207-0003
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:08:53.609074```
[ 2020-12-07 08:27:57,525 - ERROR] Failed to push to Slack
[ 2020-12-07 08:27:57,526 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ece10>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 08:53:32,785 - INFO]  *subarray_1: Completed:* 
 ``` script_description: SE-ENG linearity experiment
 pool_resources: cbf_1,sdp_1 and 55 antennas
 active_sbs: 20201207-0004
 script_name: /home/kat/usersnfs/mgouws/observation/analysis_track.py
 script_status: completed
 Duration: 0:25:35.258143```
[ 2020-12-07 09:02:01,942 - ERROR] Failed to push to Slack
[ 2020-12-07 09:02:01,942 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecf50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 09:27:32,170 - INFO]  *subarray_1: Completed:* 
 ``` pool_resources: cbf_1,sdp_1 and 55 antennas
 active_sbs: 20201207-0005
 script_status: completed
 Duration: 0:25:30.226149```
[ 2020-12-07 09:36:01,366 - ERROR] Failed to push to Slack
[ 2020-12-07 09:36:01,366 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec110>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 10:02:36,770 - INFO]  *subarray_1: Completed:* 
 ``` pool_resources: cbf_1,sdp_1 and 55 antennas
 active_sbs: 20201207-0008
 script_status: completed
 Duration: 0:26:35.402078```
[ 2020-12-07 10:11:05,942 - ERROR] Failed to push to Slack
[ 2020-12-07 10:11:05,942 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec750>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 10:48:13,398 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,sdp_1 and 18 antennas
 active_sbs: 20201207-0010
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: interrupted
 Duration: 0:02:37.427459```
[ 2020-12-07 10:56:42,582 - ERROR] Failed to push to Slack
[ 2020-12-07 10:56:42,582 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec6d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 11:11:52,775 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,sdp_1 and 18 antennas
 active_sbs: 20201207-0011
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: interrupted
 Duration: 0:02:32.807927```
[ 2020-12-07 11:20:21,974 - ERROR] Failed to push to Slack
[ 2020-12-07 11:20:21,974 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecc50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 11:31:24,771 - INFO]  *subarray_1: Completed:* 
 ``` script_description: RTS: 3.1.2.1 S-band Interferometric Phase Stability PKS1934-63 S3
 pool_resources: cbf_1,sdp_1 and 18 antennas
 active_sbs: 20201207-0012
 script_name: /home/kat/katsdpscripts/RTS/2.9-RFI/track.py
 script_status: completed
 Duration: 0:11:02.794510```
[ 2020-12-07 11:39:53,814 - ERROR] Failed to push to Slack
[ 2020-12-07 11:39:53,814 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18eca90>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 11:46:14,371 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,sdp_1 and 15 antennas
 active_sbs: 20201207-0013
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:04:24.799633```
[ 2020-12-07 11:54:43,414 - ERROR] Failed to push to Slack
[ 2020-12-07 11:54:43,414 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ece10>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 12:02:12,770 - INFO]  *subarray_1: Completed:* 
 ``` script_description: RTS: 3.1.2.1 S-band Interferometric Phase Stability PKS1934-63 S3
 pool_resources: cbf_1,sdp_1 and 15 antennas
 active_sbs: 20201207-0014
 script_name: /home/kat/katsdpscripts/RTS/2.9-RFI/track.py
 script_status: completed
 Duration: 0:07:29.353690```
[ 2020-12-07 12:10:41,878 - ERROR] Failed to push to Slack
[ 2020-12-07 12:10:41,878 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecf50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 12:36:05,171 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,ptuse_2,sdp_1 and 54 antennas
 active_sbs: 20201207-0015
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:05:07.394172```
[ 2020-12-07 12:44:34,262 - ERROR] Failed to push to Slack
[ 2020-12-07 12:44:34,262 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec550>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 12:44:34,265 - INFO]  *subarray_1: Completed:* 
 ``` script_description: UHF Phase up with flatten bandpass
 pool_resources: cbf_1,ptuse_2,sdp_1 and 54 antennas
 active_sbs: 20201207-0016
 script_name: /home/kat/katsdpscripts/observation/bf_phaseup.py
 script_status: completed
 Duration: 0:00:00.000799```
[ 2020-12-07 12:53:03,446 - ERROR] Failed to push to Slack
[ 2020-12-07 12:53:03,446 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec710>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 14:08:42,573 - INFO]  *subarray_1: Completed:* 
 ``` script_description: COM-20191129-MG-01 UHF 1K TAB coherency
 pool_resources: cbf_1,ptuse_2,sdp_1 and 54 antennas
 active_sbs: 20201207-0017
 script_name: /home/kat/usersnfs/mgeyer/katusescripts/ptuse/beamform_coherency.py
 script_status: interrupted
 Duration: 1:15:39.124332```
[ 2020-12-07 14:17:11,766 - ERROR] Failed to push to Slack
[ 2020-12-07 14:17:11,766 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecc50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 15:06:08,374 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_dev_1,sdp_1 and 55 antennas
 active_sbs: 20201207-0019
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:07:14.196728```
[ 2020-12-07 15:14:37,270 - ERROR] Failed to push to Slack
[ 2020-12-07 15:14:37,270 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec110>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 16:07:57,777 - INFO]  *subarray_1: Completed:* 
 ``` script_description: SE-ENG 32K calibrator track
 pool_resources: cbf_dev_1,sdp_1 and 55 antennas
 active_sbs: 20201207-0018
 script_name: /home/kat/usersnfs/mgouws/observation/analysis_track.py
 script_status: completed
 Duration: 0:53:20.503780```
[ 2020-12-07 16:16:26,966 - ERROR] Failed to push to Slack
[ 2020-12-07 16:16:26,966 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec850>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 16:39:18,587 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 58 antennas
 active_sbs: 20201207-0023
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:05:20.376539```
[ 2020-12-07 16:47:47,670 - ERROR] Failed to push to Slack
[ 2020-12-07 16:47:47,670 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecf50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 16:49:50,983 - INFO]  *subarray_1: Completed:* 
 ``` script_description: pointing check on J0408-6545
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 58 antennas
 active_sbs: 20201207-0025
 script_name: /home/kat/katsdpscripts/observation/reference_pointing.py
 script_status: completed
 Duration: 0:02:03.310333```
[ 2020-12-07 16:58:19,990 - ERROR] Failed to push to Slack
[ 2020-12-07 16:58:19,990 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec550>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 16:58:19,993 - INFO]  *subarray_1: Completed:* 
 ``` script_description: pointing check on J1939-6342
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 58 antennas
 active_sbs: 20201207-0024
 script_status: completed
 Duration: 0:00:00.000764```
[ 2020-12-07 17:06:49,046 - ERROR] Failed to push to Slack
[ 2020-12-07 17:06:49,046 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec6d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 17:06:49,049 - INFO]  *subarray_1: Completed:* 
 ``` script_description: pointing check on J0408-6545
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 58 antennas
 active_sbs: 20201207-0029
 script_status: completed
 Duration: 0:00:00.000811```
[ 2020-12-07 17:15:18,230 - ERROR] Failed to push to Slack
[ 2020-12-07 17:15:18,230 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec850>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 17:51:39,188 - INFO]  *subarray_1: Completed:* 
 ``` script_description: pointing check on J1939-6342
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 58 antennas
 active_sbs: 20201206-0010
 script_status: completed
 Duration: 0:36:20.956078```
[ 2020-12-07 18:00:08,278 - ERROR] Failed to push to Slack
[ 2020-12-07 18:00:08,278 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecf50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 18:00:08,280 - INFO]  *subarray_1: Completed:* 
 ``` pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 58 antennas
 active_sbs: 20201207-0031
 script_status: interrupted
 Duration: 0:00:00.000346```
[ 2020-12-07 18:08:37,462 - ERROR] Failed to push to Slack
[ 2020-12-07 18:08:37,462 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec550>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-07 23:29:53,600 - INFO]  *subarray_1: Completed:* 
 ``` script_description: MHONGOOSE J0309-41 rising 2
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 58 antennas
 active_sbs: 20201203-0034
 script_name: /usr/local/bin/astrokat-observe.py
 script_status: completed
 Duration: 5:21:16.135585```
[ 2020-12-07 23:38:22,678 - ERROR] Failed to push to Slack
[ 2020-12-07 23:38:22,678 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec6d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-08 05:06:20,792 - INFO]  *subarray_1: Completed:* 
 ``` script_description: MHONGOOSE J0429-27 setting 5
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 58 antennas
 active_sbs: 20201203-0029
 script_status: completed
 Duration: 5:27:58.112171```
[ 2020-12-08 05:14:49,942 - ERROR] Failed to push to Slack
[ 2020-12-08 05:14:49,942 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec850>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-08 05:31:55,387 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,ptuse_2,sdp_1 and 57 antennas
 active_sbs: 20201208-0001
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:05:10.184155```
[ 2020-12-08 05:40:24,278 - ERROR] Failed to push to Slack
[ 2020-12-08 05:40:24,278 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecf50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-08 05:44:45,787 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Phase up with flatten bandpass
 pool_resources: cbf_1,ptuse_2,sdp_1 and 57 antennas
 active_sbs: 20201208-0002
 script_name: /home/kat/katsdpscripts/observation/bf_phaseup.py
 script_status: completed
 Duration: 0:04:21.506461```
[ 2020-12-08 05:53:14,966 - ERROR] Failed to push to Slack
[ 2020-12-08 05:53:14,966 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec550>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-08 07:41:14,189 - INFO]  *subarray_1: Completed:* 
 ``` script_description: COM-20191129-MG-01 UHF 1K TAB coherency
 pool_resources: cbf_1,ptuse_2,sdp_1 and 57 antennas
 active_sbs: 20201208-0003
 script_name: /home/kat/usersnfs/mgeyer/katusescripts/ptuse/beamform_coherency.py
 script_status: interrupted
 Duration: 1:47:59.220733```
[ 2020-12-08 07:49:43,382 - ERROR] Failed to push to Slack
[ 2020-12-08 07:49:43,382 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec6d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-08 08:09:42,987 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,sdp_1 and 4 antennas
 active_sbs: 20201208-0004
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:04:42.199231```
[ 2020-12-08 08:18:12,182 - ERROR] Failed to push to Slack
[ 2020-12-08 08:18:12,182 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec390>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-08 10:20:27,990 - INFO]  *subarray_1: Completed:* 
 ``` script_description: 1: S-band holography high-end (3062.5MHz) scan-extent 4 scanspeed 0.05 cycle-duration 3600 tracktime 10
 pool_resources: cbf_1,sdp_1 and 4 antennas
 active_sbs: 20201208-0005
 script_name: /home/kat/katsdpscripts/observation/holography_scan.py
 script_status: interrupted
 Duration: 2:02:15.805615```
[ 2020-12-08 10:28:57,046 - ERROR] Failed to push to Slack
[ 2020-12-08 10:28:57,046 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec750>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-08 14:14:19,395 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 57 antennas
 active_sbs: 20201208-0011
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:06:34.397396```
[ 2020-12-08 14:22:48,534 - ERROR] Failed to push to Slack
[ 2020-12-08 14:22:48,534 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec850>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-08 14:47:48,596 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Meertime phase up with flatten bandpass
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 57 antennas
 active_sbs: 20201208-0009
 script_name: /home/kat/katsdpscripts/observation/bf_phaseup.py
 script_status: completed
 Duration: 0:06:51.389290```
[ 2020-12-08 14:56:17,750 - ERROR] Failed to push to Slack
[ 2020-12-08 14:56:17,750 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecf50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-08 14:56:17,753 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Fluxcal J1939-6342
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 57 antennas
 active_sbs: 20201208-0010
 script_name: /home/kat/usersnfs/sarah/beamform-multi-cal/katusescripts/ptuse/beamform_multi_cal.py
 script_status: completed
 Duration: 0:00:00.000674```
[ 2020-12-08 15:04:46,678 - ERROR] Failed to push to Slack
[ 2020-12-08 15:04:46,678 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18eca90>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-08 15:04:46,681 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Meertime phase up with flatten bandpass
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 57 antennas
 active_sbs: 20201208-0013
 script_name: /home/kat/katsdpscripts/observation/bf_phaseup.py
 script_status: interrupted
 Duration: 0:00:00.000781```
[ 2020-12-08 15:13:15,861 - ERROR] Failed to push to Slack
[ 2020-12-08 15:13:15,862 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec750>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-08 15:13:15,864 - INFO]  *subarray_1: Completed:* 
 ``` pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 57 antennas
 active_sbs: 20201208-0014
 script_status: completed
 Duration: 0:00:00.000307```
[ 2020-12-08 15:21:44,790 - ERROR] Failed to push to Slack
[ 2020-12-08 15:21:44,790 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec850>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-08 15:48:05,398 - INFO]  *subarray_1: Completed:* 
 ``` script_description: MeerTime Relbin 2020-12-07 
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 57 antennas
 active_sbs: 20201130-0023
 script_name: /home/kat/usersnfs/sarah/multi/katusescripts/ptuse/beamform_multi.py
 script_status: interrupted
 Duration: 0:26:20.606360```
[ 2020-12-08 15:56:34,518 - ERROR] Failed to push to Slack
[ 2020-12-08 15:56:34,518 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecf50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-08 16:13:43,997 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Meertime phase up with flatten bandpass
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 57 antennas
 active_sbs: 20201208-0017
 script_name: /home/kat/katsdpscripts/observation/bf_phaseup.py
 script_status: interrupted
 Duration: 0:00:24.598637```
[ 2020-12-08 16:22:13,078 - ERROR] Failed to push to Slack
[ 2020-12-08 16:22:13,078 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18eca90>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-08 16:22:13,081 - INFO]  *subarray_1: Completed:* 
 ``` pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 57 antennas
 active_sbs: 20201208-0018
 script_status: interrupted
 Duration: 0:00:00.000401```
[ 2020-12-08 16:30:42,262 - ERROR] Failed to push to Slack
[ 2020-12-08 16:30:42,262 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec750>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-08 16:30:42,264 - INFO]  *subarray_1: Completed:* 
 ``` pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 57 antennas
 active_sbs: 20201208-0019
 script_status: interrupted
 Duration: 0:00:00.000320```
[ 2020-12-08 16:39:11,449 - ERROR] Failed to push to Slack
[ 2020-12-08 16:39:11,450 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec850>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-08 16:43:05,398 - INFO]  *subarray_1: Completed:* 
 ``` pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 57 antennas
 active_sbs: 20201208-0020
 script_status: completed
 Duration: 0:03:53.946237```
[ 2020-12-08 16:51:34,486 - ERROR] Failed to push to Slack
[ 2020-12-08 16:51:34,486 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecf50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-08 16:51:34,488 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 57 antennas
 active_sbs: 20201208-0021
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:00:00.000645```
[ 2020-12-08 17:00:03,541 - ERROR] Failed to push to Slack
[ 2020-12-08 17:00:03,542 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18eca90>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-08 17:00:03,543 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Meertime phase up with flatten bandpass
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 57 antennas
 active_sbs: 20201208-0022
 script_name: /home/kat/katsdpscripts/observation/bf_phaseup.py
 script_status: completed
 Duration: 0:00:00.000390```
[ 2020-12-08 17:08:32,726 - ERROR] Failed to push to Slack
[ 2020-12-08 17:08:32,726 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec750>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-08 17:08:32,729 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Fluxcal J1939-6342
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 57 antennas
 active_sbs: 20201208-0023
 script_name: /home/kat/usersnfs/sarah/beamform-multi-cal/katusescripts/ptuse/beamform_multi_cal.py
 script_status: completed
 Duration: 0:00:00.000884```
[ 2020-12-08 17:17:01,909 - ERROR] Failed to push to Slack
[ 2020-12-08 17:17:01,910 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ec850>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-08 20:32:51,401 - INFO]  *subarray_1: Completed:* 
 ``` script_description: MeerTIME MSP regular  (2020 epoch 26) part 3
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 57 antennas
 active_sbs: 20201130-0018
 script_name: /home/kat/usersnfs/sarah/multi/katusescripts/ptuse/beamform_multi.py
 script_status: completed
 Duration: 3:15:49.489679```
[ 2020-12-08 20:41:20,470 - ERROR] Failed to push to Slack
[ 2020-12-08 20:41:20,470 - ERROR] HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36a18ecf50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[ 2020-12-08 21:35:41,810 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,sdp_1 and 57 antennas
 active_sbs: 20201208-0030
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:06:26.003541```
[ 2020-12-09 03:47:47,007 - INFO]  *subarray_1: Completed:* 
 ``` script_description:  UHF-band holography --scan-extent 15 --tracktime 5 --cycle-duration 2700 elevation-histogram
 pool_resources: cbf_1,sdp_1 and 57 antennas
 active_sbs: 20201208-0031
 script_name: /home/kat/katsdpscripts/observation/spiral_holography_scan.py
 script_status: interrupted
 Duration: 6:05:45.005514```
[ 2020-12-09 04:20:14,607 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 57 antennas
 active_sbs: 20201209-0003
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:06:17.392149```
[ 2020-12-09 04:28:46,809 - INFO]  *subarray_1: Completed:* 
 ``` pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 57 antennas
 active_sbs: 20201209-0005
 script_status: completed
 Duration: 0:04:10.202210```
[ 2020-12-09 04:37:46,207 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Meertime phase up with flatten bandpass
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 57 antennas
 active_sbs: 20201209-0001
 script_name: /home/kat/katsdpscripts/observation/bf_phaseup.py
 script_status: completed
 Duration: 0:06:43.595274```
[ 2020-12-09 04:45:33,408 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Fluxcal J0408-6545
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 57 antennas
 active_sbs: 20201209-0002
 script_name: /home/kat/usersnfs/sarah/beamform-multi-cal/katusescripts/ptuse/beamform_multi_cal.py
 script_status: completed
 Duration: 0:04:16.999771```
[ 2020-12-09 09:14:25,216 - INFO]  *subarray_1: Completed:* 
 ``` script_description: MeerTIME MSP regular  (2020 epoch 26) part 1
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 57 antennas
 active_sbs: 20201130-0020
 script_name: /home/kat/usersnfs/sarah/multi/katusescripts/ptuse/beamform_multi.py
 script_status: completed
 Duration: 4:23:05.608452```
[ 2020-12-09 09:59:57,410 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,sdp_1 and 46 antennas
 active_sbs: 20201209-0006
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:05:26.395244```
[ 2020-12-09 10:28:57,211 - INFO]  *subarray_1: Completed:* 
 ``` script_description: pointing check on J1939-6342
 pool_resources: cbf_1,sdp_1 and 46 antennas
 active_sbs: 20201209-0007
 script_name: /home/kat/katsdpscripts/observation/reference_pointing.py
 script_status: interrupted
 Duration: 0:27:47.001137```
[ 2020-12-09 12:49:24,614 - INFO]  *subarray_1: Completed:* 
 ``` script_description: Delaycal
 pool_resources: cbf_1,sdp_1 and 45 antennas
 active_sbs: 20201209-0009
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 script_status: completed
 Duration: 0:04:55.397885```
[ 2020-12-09 12:55:17,818 - INFO]  *subarray_1: Completed:* 
 ``` script_description: pointing check on J1939-6342
 pool_resources: cbf_1,sdp_1 and 45 antennas
 active_sbs: 20201209-0010
 script_name: /home/kat/katsdpscripts/observation/reference_pointing.py
 script_status: completed
 Duration: 0:04:41.601970```
[ 2020-12-09 13:16:11,414 - INFO]  *subarray_1: Completed:* 
 ``` pool_resources: cbf_1,sdp_1 and 45 antennas
 active_sbs: 20201209-0011
 script_status: completed
 Duration: 0:16:39.199701```
[ 2020-12-09 14:05:14,734 - WARNING] Websocket server disconnected!
[ 2020-12-09 14:05:14,737 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:05:14,737 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:05:29,750 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:05:29,750 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:05:44,763 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:05:44,764 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:05:59,780 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:05:59,780 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:06:14,797 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:06:14,798 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:06:29,811 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:06:29,812 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:06:44,818 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:06:44,818 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:06:59,833 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:06:59,834 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:07:14,851 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:07:14,851 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:07:29,856 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:07:29,856 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:07:44,863 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:07:44,863 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:07:59,880 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:07:59,880 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:08:14,896 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:08:14,896 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:08:29,913 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:08:29,913 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:08:44,927 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:08:44,927 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:08:59,944 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:08:59,944 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:09:14,961 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:09:14,961 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:09:29,978 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:09:29,978 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:09:44,995 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:09:44,995 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:10:00,012 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:10:00,012 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:10:15,028 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:10:15,029 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:10:30,045 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:10:30,046 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:10:45,060 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:10:45,060 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:11:00,076 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:11:00,076 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:11:15,094 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:11:15,094 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:11:30,111 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:11:30,111 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:11:45,129 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:11:45,129 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:12:00,146 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:12:00,147 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:12:15,164 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:12:15,164 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:12:30,182 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:12:30,182 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:12:45,195 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:12:45,196 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:13:00,211 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:13:00,211 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:13:15,228 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:13:15,229 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:13:30,245 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:13:30,246 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:13:45,260 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:13:45,260 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:14:00,277 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:14:00,277 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:14:15,295 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:14:15,295 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:14:30,307 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:14:30,307 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:14:45,323 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:14:45,324 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:15:00,339 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:15:00,339 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:15:15,356 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:15:15,357 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:15:30,374 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:15:30,374 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:15:45,391 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:15:45,391 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:16:00,396 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:16:00,396 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:16:15,413 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:16:15,414 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:16:30,430 - ERROR] Could not connect websocket to ws://10.97.1.14/katmetadata/subarray-1/custom/websocket
Traceback (most recent call last):
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/katportalclient-0.2.1-py2.7.egg/katportalclient/client.py", line 471, in _connect
    connect_timeout=WS_CONNECT_TIMEOUT)
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/virtualenv/bluse/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 502: Bad Gateway
[ 2020-12-09 14:16:30,431 - INFO] Retrying connection in 15 seconds...
[ 2020-12-09 14:16:45,464 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: caf44c8a1b, method: subscribe, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', None]
[ 2020-12-09 14:16:45,627 - INFO] Resent JSONRPCRequest, with result: 1
[ 2020-12-09 14:16:45,628 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: db5ff2edc7, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_1_state'], 'event', False]
[ 2020-12-09 14:16:47,511 - INFO] Resent JSONRPCRequest, with result: {u'subarray_1_state': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:47,511 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: fc9352bd17, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_2_state'], 'event', False]
[ 2020-12-09 14:16:48,416 - INFO] Resent JSONRPCRequest, with result: {u'subarray_2_state': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:48,416 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: 23efa91fd7, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_3_state'], 'event', False]
[ 2020-12-09 14:16:48,851 - INFO] Resent JSONRPCRequest, with result: {u'subarray_3_state': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:48,851 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: 922cdad5ea, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_4_state'], 'event', False]
[ 2020-12-09 14:16:49,187 - INFO] Resent JSONRPCRequest, with result: {u'subarray_4_state': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:49,188 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: d33914bea3, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_5_state'], 'event', False]
[ 2020-12-09 14:16:49,804 - INFO] Resent JSONRPCRequest, with result: {u'subarray_5_state': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:49,804 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: 950b179628, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_6_state'], 'event', False]
[ 2020-12-09 14:16:50,365 - INFO] Resent JSONRPCRequest, with result: {u'subarray_6_state': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:50,365 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: ee58fb7d52, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_1_script_description'], 'event', False]
[ 2020-12-09 14:16:50,923 - INFO] Resent JSONRPCRequest, with result: {u'subarray_1_script_description': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:50,924 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: f6c3b03e48, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_1_pool_resources'], 'event', False]
[ 2020-12-09 14:16:51,069 - INFO] Resent JSONRPCRequest, with result: {u'subarray_1_pool_resources': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:51,069 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: bed4a0ed25, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_1_script_name'], 'event', False]
[ 2020-12-09 14:16:51,178 - INFO] Resent JSONRPCRequest, with result: {u'subarray_1_script_name': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:51,178 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: a106b925c9, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_1_active_sbs'], 'event', False]
[ 2020-12-09 14:16:51,308 - INFO] Resent JSONRPCRequest, with result: {u'subarray_1_active_sbs': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:51,308 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: 0eb13957ac, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_1_script_status'], 'event', False]
[ 2020-12-09 14:16:51,462 - INFO] Resent JSONRPCRequest, with result: {u'subarray_1_script_status': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:51,462 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: 5babf57d61, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_2_script_description'], 'event', False]
[ 2020-12-09 14:16:51,623 - INFO] Resent JSONRPCRequest, with result: {u'subarray_2_script_description': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:51,624 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: 965f83870f, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_2_pool_resources'], 'event', False]
[ 2020-12-09 14:16:51,745 - INFO] Resent JSONRPCRequest, with result: {u'subarray_2_pool_resources': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:51,745 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: 849ab41fcd, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_2_script_name'], 'event', False]
[ 2020-12-09 14:16:51,858 - INFO] Resent JSONRPCRequest, with result: {u'subarray_2_script_name': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:51,858 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: 4c013fa0c9, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_2_active_sbs'], 'event', False]
[ 2020-12-09 14:16:51,962 - INFO] Resent JSONRPCRequest, with result: {u'subarray_2_active_sbs': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:51,962 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: b217060002, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_2_script_status'], 'event', False]
[ 2020-12-09 14:16:52,047 - INFO] Resent JSONRPCRequest, with result: {u'subarray_2_script_status': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:52,047 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: 490ba9723b, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_5_script_description'], 'event', False]
[ 2020-12-09 14:16:52,132 - INFO] Resent JSONRPCRequest, with result: {u'subarray_5_script_description': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:52,132 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: 1fd181aa02, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_5_pool_resources'], 'event', False]
[ 2020-12-09 14:16:52,225 - INFO] Resent JSONRPCRequest, with result: {u'subarray_5_pool_resources': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:52,225 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: 0ef8afb43c, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_5_script_name'], 'event', False]
[ 2020-12-09 14:16:52,790 - INFO] Resent JSONRPCRequest, with result: {u'subarray_5_script_name': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:52,791 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: 50f7f31400, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_5_active_sbs'], 'event', False]
[ 2020-12-09 14:16:52,889 - INFO] Resent JSONRPCRequest, with result: {u'subarray_5_active_sbs': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:52,889 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: 2c194c93d7, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_5_script_status'], 'event', False]
[ 2020-12-09 14:16:53,003 - INFO] Resent JSONRPCRequest, with result: {u'subarray_5_script_status': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:53,003 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: 4faaad97d5, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_3_script_description'], 'event', False]
[ 2020-12-09 14:16:53,095 - INFO] Resent JSONRPCRequest, with result: {u'subarray_3_script_description': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:53,095 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: f904947272, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_3_pool_resources'], 'event', False]
[ 2020-12-09 14:16:53,184 - INFO] Resent JSONRPCRequest, with result: {u'subarray_3_pool_resources': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:53,184 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: fcfdaf13df, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_3_script_name'], 'event', False]
[ 2020-12-09 14:16:53,272 - INFO] Resent JSONRPCRequest, with result: {u'subarray_3_script_name': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:53,273 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: e75684afdc, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_3_active_sbs'], 'event', False]
[ 2020-12-09 14:16:53,368 - INFO] Resent JSONRPCRequest, with result: {u'subarray_3_active_sbs': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:53,368 - INFO] Resending JSONRPCRequest <class 'katportalclient.request.JSONRPCRequest'>: id: 797e290d4a, method: set_sampling_strategies, params: ['namespace_bc734a5c-4ac2-416c-b2d0-c71edc675ee2', [u'subarray_3_script_status'], 'event', False]
[ 2020-12-09 14:16:53,508 - INFO] Resent JSONRPCRequest, with result: {u'subarray_3_script_status': {u'info': u'event', u'success': True}}
[ 2020-12-09 14:16:53,509 - INFO] Reconnected :)
[ 2020-12-09 14:35:20,246 - INFO] Subscribed to sensor: subarray_1_script_description
[ 2020-12-09 14:35:24,165 - INFO] Subscribed to sensor: subarray_1_pool_resources
[ 2020-12-09 14:35:28,664 - INFO] Subscribed to sensor: subarray_1_script_name
[ 2020-12-09 14:35:32,078 - INFO] Subscribed to sensor: subarray_1_active_sbs
[ 2020-12-09 14:35:35,480 - INFO] Subscribed to sensor: subarray_1_script_status
[ 2020-12-09 14:35:55,497 - INFO] Unsubscribed from: subarray_1_script_description
[ 2020-12-09 14:35:58,589 - INFO] Unsubscribed from: subarray_1_pool_resources
[ 2020-12-09 14:36:01,834 - INFO] Unsubscribed from: subarray_1_script_name
[ 2020-12-09 14:36:04,955 - INFO] Unsubscribed from: subarray_1_active_sbs
[ 2020-12-09 14:36:08,075 - INFO] Unsubscribed from: subarray_1_script_status
[ 2020-12-09 14:50:44,048 - INFO] Subscribed to sensor: subarray_1_script_description
[ 2020-12-09 14:50:49,435 - INFO] Subscribed to sensor: subarray_1_pool_resources
[ 2020-12-09 14:50:53,077 - INFO] Subscribed to sensor: subarray_1_script_name
[ 2020-12-09 14:50:56,499 - INFO] Subscribed to sensor: subarray_1_active_sbs
[ 2020-12-09 14:50:59,853 - INFO] Subscribed to sensor: subarray_1_script_status
[ 2020-12-09 15:01:08,531 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 pool_resources: cbf_1,sdp_1 and 50 antennas
 script_status: completed
 script_description: Delaycal
 active_sbs: 20201209-0018
 Duration: 0:06:26.190601```
[ 2020-12-09 15:02:26,929 - INFO] Unsubscribed from: subarray_1_script_description
[ 2020-12-09 15:02:30,827 - INFO] Unsubscribed from: subarray_1_pool_resources
[ 2020-12-09 15:02:34,805 - INFO] Unsubscribed from: subarray_1_script_name
[ 2020-12-09 15:02:38,404 - INFO] Unsubscribed from: subarray_1_active_sbs
[ 2020-12-09 15:02:42,352 - INFO] Unsubscribed from: subarray_1_script_status
[ 2020-12-09 15:10:55,111 - INFO] Subscribed to sensor: subarray_1_script_description
[ 2020-12-09 15:10:58,478 - INFO] Subscribed to sensor: subarray_1_pool_resources
[ 2020-12-09 15:11:03,993 - INFO] Subscribed to sensor: subarray_1_script_name
[ 2020-12-09 15:11:07,745 - INFO] Subscribed to sensor: subarray_1_active_sbs
[ 2020-12-09 15:11:11,562 - INFO] Subscribed to sensor: subarray_1_script_status
[ 2020-12-09 15:18:55,733 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 pool_resources: cbf_1,sdp_1 and 48 antennas
 script_status: completed
 script_description: Delaycal
 active_sbs: 20201209-0027
 Duration: 0:05:41.793066```
[ 2020-12-09 15:21:13,787 - INFO] Unsubscribed from: subarray_1_script_description
[ 2020-12-09 15:21:17,045 - INFO] Unsubscribed from: subarray_1_pool_resources
[ 2020-12-09 15:21:20,275 - INFO] Unsubscribed from: subarray_1_script_name
[ 2020-12-09 15:21:23,352 - INFO] Unsubscribed from: subarray_1_active_sbs
[ 2020-12-09 15:21:26,396 - INFO] Unsubscribed from: subarray_1_script_status
[ 2020-12-09 15:34:07,364 - INFO] Subscribed to sensor: subarray_1_script_description
[ 2020-12-09 15:34:11,735 - INFO] Subscribed to sensor: subarray_1_pool_resources
[ 2020-12-09 15:34:15,800 - INFO] Subscribed to sensor: subarray_1_script_name
[ 2020-12-09 15:34:20,117 - INFO] Subscribed to sensor: subarray_1_active_sbs
[ 2020-12-09 15:34:24,205 - INFO] Subscribed to sensor: subarray_1_script_status
[ 2020-12-09 15:40:33,735 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 pool_resources: cbf_1,sdp_1 and 48 antennas
 script_status: completed
 script_description: Delaycal
 active_sbs: 20201209-0030
 Duration: 0:05:08.594888```
[ 2020-12-09 16:03:16,941 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 script_name: /home/kat/katsdpscripts/observation/reference_pointing.py
 pool_resources: cbf_1,sdp_1 and 48 antennas
 script_status: completed
 script_description: pointing check on J1939-6342
 active_sbs: 20201209-0032
 Duration: 0:05:09.807030```
[ 2020-12-09 16:10:45,937 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 pool_resources: cbf_1,sdp_1 and 48 antennas
 script_status: completed
 active_sbs: 20201209-0039
 Duration: 0:05:03.602716```
[ 2020-12-09 16:17:16,142 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 pool_resources: cbf_1,sdp_1 and 48 antennas
 script_status: completed
 active_sbs: 20201209-0040
 Duration: 0:05:01.994710```
[ 2020-12-09 16:23:51,342 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 pool_resources: cbf_1,sdp_1 and 48 antennas
 script_status: completed
 active_sbs: 20201209-0041
 Duration: 0:05:05.607379```
[ 2020-12-09 16:30:33,539 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 pool_resources: cbf_1,sdp_1 and 48 antennas
 script_status: completed
 active_sbs: 20201209-0042
 Duration: 0:05:06.191342```
[ 2020-12-09 16:37:12,736 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 pool_resources: cbf_1,sdp_1 and 48 antennas
 script_status: completed
 active_sbs: 20201209-0043
 Duration: 0:05:04.799567```
[ 2020-12-09 16:43:43,938 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 pool_resources: cbf_1,sdp_1 and 48 antennas
 script_status: completed
 active_sbs: 20201209-0044
 Duration: 0:05:04.788248```
[ 2020-12-09 16:45:42,336 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 pool_resources: cbf_1,sdp_1 and 48 antennas
 script_status: interrupted
 active_sbs: 20201209-0047
 Duration: 0:00:07.194062```
[ 2020-12-09 16:54:34,007 - INFO] Unsubscribed from: subarray_1_script_description
[ 2020-12-09 16:54:37,142 - INFO] Unsubscribed from: subarray_1_pool_resources
[ 2020-12-09 16:54:40,783 - INFO] Unsubscribed from: subarray_1_script_name
[ 2020-12-09 16:54:44,123 - INFO] Unsubscribed from: subarray_1_active_sbs
[ 2020-12-09 16:54:47,420 - INFO] Unsubscribed from: subarray_1_script_status
[ 2020-12-09 17:05:16,531 - INFO] Subscribed to sensor: subarray_1_script_description
[ 2020-12-09 17:05:20,593 - INFO] Subscribed to sensor: subarray_1_pool_resources
[ 2020-12-09 17:05:24,571 - INFO] Subscribed to sensor: subarray_1_script_name
[ 2020-12-09 17:05:28,546 - INFO] Subscribed to sensor: subarray_1_active_sbs
[ 2020-12-09 17:05:32,477 - INFO] Subscribed to sensor: subarray_1_script_status
[ 2020-12-09 17:13:44,945 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 59 antennas
 script_status: completed
 script_description: Delaycal
 active_sbs: 20201209-0059
 Duration: 0:05:48.397918```
[ 2020-12-09 17:36:29,337 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 script_name: /home/kat/katsdpscripts/observation/reference_pointing.py
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 59 antennas
 script_status: completed
 script_description: pointing check on J1939-6342
 active_sbs: 20201209-0048
 Duration: 0:06:30.801212```
[ 2020-12-09 17:44:30,945 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 59 antennas
 script_status: completed
 active_sbs: 20201209-0060
 Duration: 0:06:25.000096```
[ 2020-12-09 17:52:40,536 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 59 antennas
 script_status: completed
 active_sbs: 20201209-0061
 Duration: 0:06:24.389896```
[ 2020-12-09 23:04:42,942 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 script_name: /usr/local/bin/astrokat-observe.py
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 59 antennas
 script_status: completed
 script_description: mfs05a
 active_sbs: 20201207-0006
 Duration: 5:08:38.593948```
[ 2020-12-10 04:45:07,547 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 pool_resources: cbf_1,fbfuse_1,sdp_1,tuse_1 and 59 antennas
 script_status: completed
 script_description: MHONGOOSE J0429-27 setting 4
 active_sbs: 20201203-0028
 Duration: 5:33:58.988122```
[ 2020-12-10 04:47:46,686 - INFO] Unsubscribed from: subarray_1_script_description
[ 2020-12-10 04:47:49,825 - INFO] Unsubscribed from: subarray_1_pool_resources
[ 2020-12-10 04:47:53,005 - INFO] Unsubscribed from: subarray_1_script_name
[ 2020-12-10 04:47:56,086 - INFO] Unsubscribed from: subarray_1_active_sbs
[ 2020-12-10 04:47:59,070 - INFO] Unsubscribed from: subarray_1_script_status
[ 2020-12-10 05:05:35,995 - INFO] Subscribed to sensor: subarray_1_script_description
[ 2020-12-10 05:05:40,035 - INFO] Subscribed to sensor: subarray_1_pool_resources
[ 2020-12-10 05:05:44,237 - INFO] Subscribed to sensor: subarray_1_script_name
[ 2020-12-10 05:05:48,531 - INFO] Subscribed to sensor: subarray_1_active_sbs
[ 2020-12-10 05:05:52,477 - INFO] Subscribed to sensor: subarray_1_script_status
[ 2020-12-10 05:12:21,344 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 60 antennas
 script_status: completed
 script_description: Delaycal
 active_sbs: 20201210-0003
 Duration: 0:05:09.991370```
[ 2020-12-10 05:32:53,143 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 script_name: /home/kat/katsdpscripts/observation/bf_phaseup.py
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 60 antennas
 script_status: completed
 script_description: Meertime phase up with flatten bandpass
 active_sbs: 20201210-0001
 Duration: 0:06:55.599391```
[ 2020-12-10 05:40:30,552 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 script_name: /home/kat/usersnfs/sarah/beamform-multi-cal/katusescripts/ptuse/beamform_multi_cal.py
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 60 antennas
 script_status: completed
 script_description: Fluxcal J0408-6545
 active_sbs: 20201210-0002
 Duration: 0:04:17.408857```
[ 2020-12-10 07:50:35,347 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 script_name: /home/kat/usersnfs/sarah/multi/katusescripts/ptuse/beamform_multi.py
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 60 antennas
 script_status: completed
 script_description: MeerTime Relbin 2020-12 J1439-5501 (rising)
 active_sbs: 20201207-0032
 Duration: 2:04:18.802426```
[ 2020-12-10 07:55:01,533 - INFO] Unsubscribed from: subarray_1_script_description
[ 2020-12-10 07:55:04,969 - INFO] Unsubscribed from: subarray_1_pool_resources
[ 2020-12-10 07:55:08,443 - INFO] Unsubscribed from: subarray_1_script_name
[ 2020-12-10 07:55:11,820 - INFO] Unsubscribed from: subarray_1_active_sbs
[ 2020-12-10 07:55:15,306 - INFO] Unsubscribed from: subarray_1_script_status
[ 2020-12-10 08:18:45,852 - INFO] Subscribed to sensor: subarray_2_script_description
[ 2020-12-10 08:18:51,574 - INFO] Subscribed to sensor: subarray_2_pool_resources
[ 2020-12-10 08:18:55,339 - INFO] Subscribed to sensor: subarray_2_script_name
[ 2020-12-10 08:18:58,928 - INFO] Subscribed to sensor: subarray_2_active_sbs
[ 2020-12-10 08:19:02,524 - INFO] Subscribed to sensor: subarray_2_script_status
[ 2020-12-10 08:28:14,876 - INFO] Unsubscribed from: subarray_2_script_description
[ 2020-12-10 08:28:18,287 - INFO] Unsubscribed from: subarray_2_pool_resources
[ 2020-12-10 08:28:21,816 - INFO] Unsubscribed from: subarray_2_script_name
[ 2020-12-10 08:28:25,174 - INFO] Unsubscribed from: subarray_2_active_sbs
[ 2020-12-10 08:28:28,483 - INFO] Unsubscribed from: subarray_2_script_status
[ 2020-12-10 08:38:13,040 - INFO] Subscribed to sensor: subarray_2_script_description
[ 2020-12-10 08:38:16,417 - INFO] Subscribed to sensor: subarray_2_pool_resources
[ 2020-12-10 08:38:19,783 - INFO] Subscribed to sensor: subarray_2_script_name
[ 2020-12-10 08:38:23,131 - INFO] Subscribed to sensor: subarray_2_active_sbs
[ 2020-12-10 08:38:27,912 - INFO] Subscribed to sensor: subarray_2_script_status
[ 2020-12-10 08:39:14,850 - INFO] Subscribed to sensor: subarray_1_script_description
[ 2020-12-10 08:39:18,513 - INFO] Subscribed to sensor: subarray_1_pool_resources
[ 2020-12-10 08:39:22,064 - INFO] Subscribed to sensor: subarray_1_script_name
[ 2020-12-10 08:39:25,749 - INFO] Subscribed to sensor: subarray_1_active_sbs
[ 2020-12-10 08:39:29,286 - INFO] Subscribed to sensor: subarray_1_script_status
[ 2020-12-10 08:48:09,946 - INFO]  *subarray_2: Completed:* 
 ``` state: active
 script_name: /home/kat/katsdpscripts/RTS/2.2-T_sys_T_nd/skyloadcal.py
 pool_resources: cbf_2,sdp_2 and 1 antennas
 script_status: completed
 script_description: Hotload and Coldload observation:RTS: 2.2 UHF T_sys_T_nd 
 active_sbs: 20201130-0034
 Duration: 0:04:54.399687```
[ 2020-12-10 08:48:58,147 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 pool_resources: cbf_1,sdp_1 and 18 antennas
 script_status: completed
 script_description: Delaycal
 active_sbs: 20201210-0004
 Duration: 0:05:01.989337```
[ 2020-12-10 08:54:44,347 - INFO]  *subarray_2: Completed:* 
 ``` state: active
 pool_resources: cbf_2,sdp_2 and 1 antennas
 script_status: completed
 active_sbs: 20201210-0006
 Duration: 0:03:45.202241```
[ 2020-12-10 08:59:00,545 - INFO]  *subarray_2: Completed:* 
 ``` state: active
 pool_resources: cbf_2,sdp_2 and 1 antennas
 script_status: completed
 active_sbs: 20201210-0005
 Duration: 0:03:43.800405```
[ 2020-12-10 09:02:19,746 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 pool_resources: cbf_1,sdp_1 and 18 antennas
 script_status: completed
 active_sbs: 20201210-0007
 Duration: 0:03:58.800448```
[ 2020-12-10 10:33:20,148 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 script_name: /home/kat/katsdpscripts/RTS/2.9-RFI/track.py
 pool_resources: cbf_1,sdp_1 and 18 antennas
 script_status: completed
 script_description: RTS: 3.1.2.1 S-band Interferometric Phase Stability PKS1934-63 S3
 active_sbs: 20201210-0008
 Duration: 1:00:17.593722```
[ 2020-12-10 12:40:48,551 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 script_name: /home/kat/katsdpscripts/observation/interferometric_pointing.py
 pool_resources: cbf_1,sdp_1 and 18 antennas
 script_status: interrupted
 script_description: RTS: S-band Interferometric Pointing Calibration 
 active_sbs: 20201210-0009
 Duration: 2:06:38.404245```
[ 2020-12-10 12:41:31,019 - INFO] Unsubscribed from: subarray_2_script_description
[ 2020-12-10 12:41:34,145 - INFO] Unsubscribed from: subarray_2_pool_resources
[ 2020-12-10 12:41:37,342 - INFO] Unsubscribed from: subarray_2_script_name
[ 2020-12-10 12:41:40,379 - INFO] Unsubscribed from: subarray_2_active_sbs
[ 2020-12-10 12:41:43,760 - INFO] Unsubscribed from: subarray_2_script_status
[ 2020-12-10 12:44:29,972 - INFO] Unsubscribed from: subarray_1_script_description
[ 2020-12-10 12:44:33,289 - INFO] Unsubscribed from: subarray_1_pool_resources
[ 2020-12-10 12:44:36,768 - INFO] Unsubscribed from: subarray_1_script_name
[ 2020-12-10 12:44:40,125 - INFO] Unsubscribed from: subarray_1_active_sbs
[ 2020-12-10 12:44:43,425 - INFO] Unsubscribed from: subarray_1_script_status
[ 2020-12-10 12:55:05,919 - INFO] Subscribed to sensor: subarray_1_script_description
[ 2020-12-10 12:55:09,352 - INFO] Subscribed to sensor: subarray_1_pool_resources
[ 2020-12-10 12:55:12,935 - INFO] Subscribed to sensor: subarray_1_script_name
[ 2020-12-10 12:55:16,604 - INFO] Subscribed to sensor: subarray_1_active_sbs
[ 2020-12-10 12:55:20,154 - INFO] Subscribed to sensor: subarray_1_script_status
[ 2020-12-10 13:05:55,752 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 script_name: /home/kat/katsdpscripts/observation/calibrate_delays.py
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 59 antennas
 script_status: completed
 script_description: Delaycal
 active_sbs: 20201210-0012
 Duration: 0:06:53.786005```
[ 2020-12-10 13:17:49,552 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 script_name: /home/kat/katsdpscripts/observation/bf_phaseup.py
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 59 antennas
 script_status: completed
 script_description: Meertime phase up with flatten bandpass
 active_sbs: 20201208-0007
 Duration: 0:06:48.799929```
[ 2020-12-10 13:25:37,754 - INFO]  *subarray_1: Completed:* 
 ``` state: active
 script_name: /home/kat/usersnfs/sarah/beamform-multi-cal/katusescripts/ptuse/beamform_multi_cal.py
 pool_resources: cbf_1,fbfuse_1,ptuse_4,sdp_1,tuse_1 and 59 antennas
 script_status: completed
 script_description: Fluxcal J1939-6342
 active_sbs: 20201208-0008
 Duration: 0:04:19.401621```
